version: '3.7'

services:
  postgres:
    image: postgres:16.3
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: vps_deployment
      POSTGRES_PASSWORD: "Kw_-rhIWhMG9eCszxaHK9x8-MItIjMZw"
    volumes:
      - vps_deployment_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "IEG3skrg-a7DW7YDwVkk3B7fIW90n1FH"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  vps_deployment_data:
